name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Front Repository
        uses: actions/checkout@v3

      - name: Deploy Front via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/ystudent/ystudent-front
            git pull origin main
            docker compose -f ~/ystudent/docker-compose.yml build front
            docker compose -f ~/ystudent/docker-compose.yml up -d front
